// Databricks notebook source
// MAGIC %sql
// MAGIC DROP TABLE IF EXISTS F0;
// MAGIC CREATE TABLE IF NOT EXISTS F0 (
// MAGIC COD_SOCIEDAD STRING,
// MAGIC COD_POLIZA STRING,
// MAGIC COD_RAMO STRING,
// MAGIC COD_MODALIDAD STRING,
// MAGIC COD_GARANTIA STRING,
// MAGIC COD_CERTIFICADO STRING,
// MAGIC COD_RECIBO STRING,
// MAGIC MAR_NUEV_RECIBO STRING,
// MAGIC COD_DIVISA STRING,
// MAGIC IMP_PRIM_TARIFA DECIMAL(13,2),
// MAGIC IMP_PRIM_UNIC DECIMAL(13,2),
// MAGIC IMP_PRIM_PERIOD DECIMAL(13,2),
// MAGIC IMP_PRIM_EXTOR_EJER DECIMAL(13,2),
// MAGIC IMP_PRIM_EXTOR_EJER_ANT DECIMAL(13,2),
// MAGIC IMP_PRIM_ANUL_EJER_ANT DECIMAL(13,2),
// MAGIC BON_N_SINIESTRALIDAD DECIMAL(13,2),
// MAGIC IPS DECIMAL(13,2),
// MAGIC TAS_CSS_REC_RIES_EXTR DECIMAL(13,2),
// MAGIC TAS_CSS_REC_FUN_LIQ DECIMAL(13,2),
// MAGIC TAS_CSS_PRIM_PEND_COBR DECIMAL(13,2), --estaba como INT
// MAGIC ARB_BOMBEROS DECIMAL(13,2),
// MAGIC IMP_COMISIONES DECIMAL(13,2),
// MAGIC IMP_RETEN_FISC DECIMAL(13,2),
// MAGIC IMP_TOT_RECIB DECIMAL(13,2),
// MAGIC CAR_RECIB STRING,
// MAGIC ID_MOV_ECON STRING,
// MAGIC FEC_MOV_ECON STRING,
// MAGIC FEC_EMI STRING,
// MAGIC FEC_LIQ STRING,
// MAGIC COD_TIP_RECIB STRING,
// MAGIC COD_EST_REC_ANT STRING,
// MAGIC COD_EST_REC STRING,
// MAGIC REC_FRACCIONADO STRING,
// MAGIC MAR_RECIB_SIMUL STRING,
// MAGIC COMP STRING,
// MAGIC MAR_REINV STRING,
// MAGIC ENT_COLABORADORA STRING,
// MAGIC COD_TIP_SIN STRING,
// MAGIC COD_AGENCIA STRING,
// MAGIC COD_MEDIADOR STRING,
// MAGIC COD_TIP_GESTION STRING,
// MAGIC CON_LIQUIDACION STRING,
// MAGIC IMP_DESCUENTO DECIMAL(13,2),
// MAGIC IMP_PRIM_REAL DECIMAL(13,2),
// MAGIC IMP_COA DECIMAL(13,2),
// MAGIC PRE_RECOBRADAS DECIMAL(13,2), -- INT
// MAGIC NOM_DESTINATARIO STRING,
// MAGIC NOM_POBL STRING,
// MAGIC NIF STRING,
// MAGIC CTA_BANC STRING,
// MAGIC ENT_BANCARIA STRING,
// MAGIC TR_COD_RAMO_CONT STRING,
// MAGIC TR_COD_MOD_CONT STRING)
// MAGIC USING DELTA
// MAGIC TBLPROPERTIES (delta.enableChangeDataFeed = true);

// COMMAND ----------

// MAGIC %sql
// MAGIC DROP TABLE IF EXISTS f1;
// MAGIC CREATE TABLE IF NOT EXISTS f1 (
// MAGIC TR_ID_EVNEG STRING,
// MAGIC COD_SOCIEDAD STRING,
// MAGIC COD_POLIZA STRING,
// MAGIC COD_RAMO STRING,
// MAGIC COD_MODALIDAD STRING,
// MAGIC COD_GARANTIA STRING,
// MAGIC COD_CERTIFICADO STRING,
// MAGIC COD_RECIBO STRING,
// MAGIC MAR_NUEV_RECIBO STRING,
// MAGIC COD_DIVISA STRING,
// MAGIC IMP_PRIM_TARIFA DECIMAL(13,2),
// MAGIC IMP_PRIM_UNIC DECIMAL(13,2),
// MAGIC IMP_PRIM_PERIOD DECIMAL(13,2),
// MAGIC IMP_PRIM_EXTOR_EJER DECIMAL(13,2),
// MAGIC IMP_PRIM_EXTOR_EJER_ANT DECIMAL(13,2),
// MAGIC IMP_PRIM_ANUL_EJER_ANT DECIMAL(13,2),
// MAGIC BON_N_SINIESTRALIDAD DECIMAL(13,2),
// MAGIC IPS DECIMAL(13,2),
// MAGIC TAS_CSS_REC_RIES_EXTR DECIMAL(13,2),
// MAGIC TAS_CSS_REC_FUN_LIQ DECIMAL(13,2),
// MAGIC TAS_CSS_PRIM_PEND_COBR DECIMAL(13,2),
// MAGIC ARB_BOMBEROS DECIMAL(13,2),
// MAGIC IMP_COMISIONES DECIMAL(13,2),
// MAGIC IMP_RETEN_FISC DECIMAL(13,2),
// MAGIC IMP_TOT_RECIB DECIMAL(13,2),
// MAGIC CAR_RECIB STRING,
// MAGIC ID_MOV_ECON STRING,
// MAGIC FEC_MOV_ECON STRING,
// MAGIC FEC_EMI STRING,
// MAGIC FEC_LIQ STRING,
// MAGIC COD_TIP_RECIB STRING,
// MAGIC COD_EST_REC_ANT STRING,
// MAGIC COD_EST_REC STRING,
// MAGIC REC_FRACCIONADO STRING,
// MAGIC MAR_RECIB_SIMUL STRING,
// MAGIC COMP STRING,
// MAGIC MAR_REINV STRING,
// MAGIC ENT_COLABORADORA STRING,
// MAGIC COD_TIP_SIN STRING,
// MAGIC COD_AGENCIA STRING,
// MAGIC COD_MEDIADOR STRING,
// MAGIC COD_TIP_GESTION STRING,
// MAGIC CON_LIQUIDACION STRING,
// MAGIC IMP_DESCUENTO DECIMAL(13,2),
// MAGIC IMP_PRIM_REAL DECIMAL(13,2),
// MAGIC IMP_COA DECIMAL(13,2),
// MAGIC PRE_RECOBRADAS DECIMAL(13,2),
// MAGIC NOM_DESTINATARIO STRING,
// MAGIC NOM_POBL STRING,
// MAGIC NIF STRING,
// MAGIC CTA_BANC STRING,
// MAGIC ENT_BANCARIA STRING,
// MAGIC TR_COD_RAMO_CONT STRING,
// MAGIC TR_COD_MOD_CONT STRING,
// MAGIC TR_COD_TIP_RECIB STRING,
// MAGIC TR_COD_EST_RECIB STRING,
// MAGIC TR_COD_AGENCIA STRING,
// MAGIC TR_NEGOCIO STRING,
// MAGIC TR_COD_TIP_NEGOCIO STRING)
// MAGIC USING delta
// MAGIC TBLPROPERTIES (delta.enableChangeDataFeed = true);

// COMMAND ----------

// MAGIC %sql
// MAGIC CREATE TABLE IF NOT EXISTS f2_cont (
// MAGIC TR_ID_EVNEG STRING, -- Campo calculado. Identificador de evento de negocio único.
// MAGIC TR_COD_RAMO_CONT STRING, -- Proviene de F1 (campo TR_RAMO_CON)
// MAGIC TR_COD_MOD_CONT STRING, -- Proviende de F1 (campo TR_MODALIDAD_CON)
// MAGIC TR_CUENTA_CONT DECIMAL(10,0), -- Proviene de Asientos - Cuentas contables (campo COD_CUENTA)
// MAGIC TR_COD_TIP_EVCON STRING, -- Proviene de Maestro de eventos contables (Dos primeros caracteres campo COD_ASIENTO)
// MAGIC TR_ID_EVCON STRING, -- Proviene de Maestro de eventos contables (campo COD_ASIENTO)
// MAGIC TR_NAT_EVCON STRING, -- Proviene de Asientos - Estructura básica (campo NATURALEZA)
// MAGIC TR_CC_DES STRING, -- Campo calculado. Utiliza campo DESC_CUENTA de Maestro cuentas junto con campo COD_MEDIADOR de la tabla F1.
// MAGIC TR_CC_IMP DECIMAL(13,2) -- Campo calculado. Se ha tomado el valor de la columna NOM_IMPORTE de la tabla Asientos - Estructura básica para extraer el importe de la columna correspondiente de F1.
// MAGIC ) USING delta
// MAGIC TBLPROPERTIES (delta.enableChangeDataFeed = true);

// COMMAND ----------

// MAGIC %sql
// MAGIC CREATE TABLE IF NOT EXISTS ps (
// MAGIC COD_SOCIEDAD STRING, -- Priviene de F1 (COD_SOCIEDAD)
// MAGIC CLASE_DOC STRING, -- Proviene de F2_CONT (TR_COD_TIP_EVCON)
// MAGIC REFER STRING, -- Proviende de F2_CONT (TR_ID_EVCON)
// MAGIC DIV STRING, -- Proviene de F1 (COD_DIVISA)
// MAGIC TEX_CABECERA STRING, -- Proviene de F1 (CON_LIQUIDACION)
// MAGIC FECHA_CONTAB STRING, -- Campo calculado con la fecha de hoy (ddMMaaaa)
// MAGIC CLAVE_CONTAB STRING, -- Proviene de F2_CONT (TR_NAT_EVCON)
// MAGIC TERC STRING, -- Proviene de F1 (COD_MEDIADOR)
// MAGIC NOM_1 STRING, -- Nuevo (por ahora vacio)
// MAGIC NOM_2 STRING, -- Nuevo (por ahora vacio)
// MAGIC POBL STRING, -- Nuevo (por ahora vacio)
// MAGIC NIF STRING, -- Nuevo (por ahora vacio)
// MAGIC NUM_CUENTA DECIMAL(10,0), -- Proviene de F2_CONT (TR_CUENTA_CONT)
// MAGIC IMP DECIMAL(13,2), -- Proviene de F2_CONT (TR_CC_IMP) -> Campo agregado
// MAGIC DIVIS STRING, -- Proviene de F1 (TR_COD_AGENCIA)
// MAGIC C_COSTE STRING, -- Nuevo (por ahora vacio)
// MAGIC ASIG STRING, -- Nuevo (por ahora vacio)
// MAGIC TEXT STRING, -- Nuevo (por ahora vacio)
// MAGIC RAMO_CON STRING, -- Proviene de F2_CONT (TR_COD_RAMO_CONT)
// MAGIC CANL STRING, -- Nuevo (por ahora vacio)
// MAGIC INDICADOR_CME STRING, -- Nuevo (por ahora vacio)
// MAGIC MODALIDAD_CON STRING -- Proviene de F2_CONT (TR_COD_MOD_CONT)
// MAGIC ) USING delta
// MAGIC TBLPROPERTIES (delta.enableChangeDataFeed = true);
