-- Databricks notebook source
set spark.databricks.delta.properties.defaults.enableChangeDataFeed = true;

-- COMMAND ----------

DROP TABLE IF EXISTS F0;
CREATE TABLE IF NOT EXISTS F0
(COD_SOCIEDAD STRING,
COD_POLIZA STRING,
COD_RAMO STRING,
COD_MODALIDAD STRING,
COD_GARANTIA STRING,
COD_CERTIFICADO STRING,
COD_RECIBO STRING,
MAR_NUEV_RECIBO STRING,
COD_DIVISA STRING,
IMP_PRIM_TARIFA DECIMAL(13,2),
IMP_PRIM_UNIC DECIMAL(13,2),
IMP_PRIM_PERIOD DECIMAL(13,2),
IMP_PRIM_EXTOR_EJER DECIMAL(13,2),
IMP_PRIM_EXTOR_EJER_ANT DECIMAL(13,2),
IMP_PRIM_ANUL_EJER_ANT DECIMAL(13,2),
BON_N_SINIESTRALIDAD DECIMAL(13,2),
IPS DECIMAL(13,2),
TAS_CSS_REC_RIES_EXTR DECIMAL(13,2),
TAS_CSS_REC_FUN_LIQ DECIMAL(13,2),
TAS_CSS_PRIM_PEND_COBR DECIMAL(13,2), --estaba como INT
ARB_BOMBEROS DECIMAL(13,2),
IMP_COMISIONES DECIMAL(13,2),
IMP_RETEN_FISC DECIMAL(13,2),
IMP_TOT_RECIB DECIMAL(13,2),
CAR_RECIB STRING,
ID_MOV_ECON STRING,
FEC_MOV_ECON STRING,
FEC_EMI STRING,
FEC_LIQ STRING,
COD_TIP_RECIB STRING,
COD_EST_REC_ANT STRING,
COD_EST_REC STRING,
REC_FRACCIONADO STRING,
MAR_RECIB_SIMUL STRING,
COMP STRING,
MAR_REINV STRING,
ENT_COLABORADORA STRING,
COD_TIP_SIN STRING,
COD_AGENCIA STRING,
COD_MEDIADOR STRING,
COD_TIP_GESTION STRING,
CON_LIQUIDACION STRING,
IMP_DESCUENTO DECIMAL(13,2),
IMP_PRIM_REAL DECIMAL(13,2),
IMP_COA DECIMAL(13,2),
PRE_RECOBRADAS DECIMAL(13,2), -- INT
NOM_DESTINATARIO STRING,
NOM_POBL STRING,
NIF STRING,
CTA_BANC STRING,
ENT_BANCARIA STRING,
TR_COD_RAMO_CONT STRING,
TR_COD_MOD_CONT STRING)

-- COMMAND ----------

DROP TABLE IF EXISTS f1;
CREATE TABLE IF NOT EXISTS f1 (
TR_ID_EVNEG STRING,
COD_SOCIEDAD STRING,
COD_POLIZA STRING,
COD_RAMO STRING,
COD_MODALIDAD STRING,
COD_GARANTIA STRING,
COD_CERTIFICADO STRING,
COD_RECIBO STRING,
MAR_NUEV_RECIBO STRING,
COD_DIVISA STRING,
IMP_PRIM_TARIFA DECIMAL(13,2),
IMP_PRIM_UNIC DECIMAL(13,2),
IMP_PRIM_PERIOD DECIMAL(13,2),
IMP_PRIM_EXTOR_EJER DECIMAL(13,2),
IMP_PRIM_EXTOR_EJER_ANT DECIMAL(13,2),
IMP_PRIM_ANUL_EJER_ANT DECIMAL(13,2),
BON_N_SINIESTRALIDAD DECIMAL(13,2),
IPS DECIMAL(13,2),
TAS_CSS_REC_RIES_EXTR DECIMAL(13,2),
TAS_CSS_REC_FUN_LIQ DECIMAL(13,2),
TAS_CSS_PRIM_PEND_COBR DECIMAL(13,2),
ARB_BOMBEROS DECIMAL(13,2),
IMP_COMISIONES DECIMAL(13,2),
IMP_RETEN_FISC DECIMAL(13,2),
IMP_TOT_RECIB DECIMAL(13,2),
CAR_RECIB STRING,
ID_MOV_ECON STRING,
FEC_MOV_ECON STRING,
FEC_EMI STRING,
FEC_LIQ STRING,
COD_TIP_RECIB STRING,
COD_EST_REC_ANT STRING,
COD_EST_REC STRING,
REC_FRACCIONADO STRING,
MAR_RECIB_SIMUL STRING,
COMP STRING,
MAR_REINV STRING,
ENT_COLABORADORA STRING,
COD_TIP_SIN STRING,
COD_AGENCIA STRING,
COD_MEDIADOR STRING,
COD_TIP_GESTION STRING,
CON_LIQUIDACION STRING,
IMP_DESCUENTO DECIMAL(13,2),
IMP_PRIM_REAL DECIMAL(13,2),
IMP_COA DECIMAL(13,2),
PRE_RECOBRADAS DECIMAL(13,2),
NOM_DESTINATARIO STRING,
NOM_POBL STRING,
NIF STRING,
CTA_BANC STRING,
ENT_BANCARIA STRING,
TR_COD_RAMO_CONT STRING,
TR_COD_MOD_CONT STRING,
TR_COD_TIP_RECIB STRING,
TR_COD_EST_RECIB STRING,
TR_COD_AGENCIA STRING,
TR_NEGOCIO STRING,
TR_COD_TIP_NEGOCIO STRING)
USING DELTA

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS f2_cont (
TR_ID_EVNEG STRING, -- Campo calculado. Identificador de evento de negocio único.
TR_COD_RAMO_CONT STRING, -- Proviene de F1 (campo TR_RAMO_CON)
TR_COD_MOD_CONT STRING, -- Proviende de F1 (campo TR_MODALIDAD_CON)
TR_CUENTA_CONT DECIMAL(10,0), -- Proviene de Asientos - Cuentas contables (campo COD_CUENTA)
TR_COD_TIP_EVCON STRING, -- Proviene de Maestro de eventos contables (Dos primeros caracteres campo COD_ASIENTO)
TR_ID_EVCON STRING, -- Proviene de Maestro de eventos contables (campo COD_ASIENTO)
TR_NAT_EVCON STRING, -- Proviene de Asientos - Estructura básica (campo NATURALEZA)
TR_CC_DES STRING, -- Campo calculado. Utiliza campo DESC_CUENTA de Maestro cuentas junto con campo COD_MEDIADOR de la tabla F1.
TR_CC_IMP DECIMAL(13,2) -- Campo calculado. Se ha tomado el valor de la columna NOM_IMPORTE de la tabla Asientos - Estructura básica para extraer el importe de la columna correspondiente de F1.
)
USING DELTA

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ps (
COD_SOCIEDAD STRING, -- Priviene de F1 (COD_SOCIEDAD)
CLASE_DOC STRING, -- Proviene de F2_CONT (TR_COD_TIP_EVCON)
REFER STRING, -- Proviende de F2_CONT (TR_ID_EVCON)
DIV STRING, -- Proviene de F1 (COD_DIVISA)
TEX_CABECERA STRING, -- Proviene de F1 (CON_LIQUIDACION)
FECHA_CONTAB STRING, -- Campo calculado con la fecha de hoy (ddMMaaaa)
CLAVE_CONTAB STRING, -- Proviene de F2_CONT (TR_NAT_EVCON)
TERC STRING, -- Proviene de F1 (COD_MEDIADOR)
NOM_1 STRING, -- Nuevo (por ahora vacio)
NOM_2 STRING, -- Nuevo (por ahora vacio)
POBL STRING, -- Nuevo (por ahora vacio)
NIF STRING, -- Nuevo (por ahora vacio)
NUM_CUENTA DECIMAL(10,0), -- Proviene de F2_CONT (TR_CUENTA_CONT)
IMP DECIMAL(13,2), -- Proviene de F2_CONT (TR_CC_IMP) -> Campo agregado
DIVIS STRING, -- Proviene de F1 (TR_COD_AGENCIA)
C_COSTE STRING, -- Nuevo (por ahora vacio)
ASIG STRING, -- Nuevo (por ahora vacio)
TEXT STRING, -- Nuevo (por ahora vacio)
RAMO_CON STRING, -- Proviene de F2_CONT (TR_COD_RAMO_CONT)
CANL STRING, -- Nuevo (por ahora vacio)
INDICADOR_CME STRING, -- Nuevo (por ahora vacio)
MODALIDAD_CON STRING -- Proviene de F2_CONT (TR_COD_MOD_CONT)
)
USING DELTA
